name: Kubernetes deployment

on:
  push:
    branches:
      - main


env:
  FRONTEND_IMAGE: homa221/3tier-frontend
  BACKEND_IMAGE: homa221/3tier-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env for client
      run: 
        echo "REACT_APP_API_UR"=${{ secrets.REACT_APP_API_UR }} > application/client/.env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./application/client
        push: true
        tags: ${{ env.FRONTEND_IMAGE }}:latest
    
    - name: Build and push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./application/server
        push: true
        tags: ${{ env.BACKEND_IMAGE }}:latest

    

        
        


    
  